# Generated by Django 2.0.2 on 2018-02-02 17:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BcDataCollected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'bc_data_collected',
            },
        ),
        migrations.CreateModel(
            name='BcFieldTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bc_field_types',
            },
        ),
        migrations.CreateModel(
            name='BcInsurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BcRiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_types', to='main.BcInsurer')),
            ],
            options={
                'db_table': 'bc_risk_type',
            },
        ),
        migrations.AddField(
            model_name='bcdatacollected',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_collected', to='main.BcRiskType'),
        ),
    ]
