# Generated by Django 2.0.2 on 2018-02-02 17:38

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcrisktype',
            name='field2',
            field=django.contrib.postgres.fields.hstore.HStoreField(),
            preserve_default=False,
        ),
    ]
