# Generated by Django 2.0.2 on 2018-02-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bcrisktype_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcrisktype',
            name='field2',
        ),
    ]
