# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bcrisktype_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcrisktype',
            name='field2',
        ),
    ]
