# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_bcrisktype_field2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcinsurer',
            name='name',
            field=models.CharField(max_length=265),
        ),
    ]
